### ISSUE TITLE
Epic: Styling

### ISSUE THREAD

**Issue by jasminechatfield** [drugsandwires/drugsandwires#12]
- [ ] #11 
- [ ] Style homepage
- [ ] Style comments in Hyvor
- [ ] Style comic page
- [ ] Style character index
- [ ] Style character page
- [ ] Style about page / generic page
- [ ] Style news index
- [ ] Style individual news page
